### ISSUE TITLE
/var/lib/unifi-video/videos mounted as root

### ISSUE THREAD

**Issue by hollanbm** [pducharme/UniFi-Video-Controller#152]
Ubuntu Server 18.04.3 LTS

```
version: '3.7'
services:
  unifi-video:
    container_name: unifi-video
    image: pducharme/unifi-video-controller
    restart: always
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Kentucky/Louisville # timezone
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${HOME}/Services/UniFi-Video/unifi-video:/var/lib/unifi-video
      - ${HOME}/Surveillance:/var/lib/unifi-video/videos
```

${HOME}/Surveillance: is an NFS mount, mapped to user:user (1000:1000)
```
user@unifi-video:~$ ls -l
total 75
drwxr-xr-x 3 user user 4096 Sep  4 22:57 Services
drwxrwxr-x 9 user user   16 Sep  4 22:56 Share
drwxr-xr-x 2 user user    2 Sep  4 22:55 Surveillance
user@unifi-video:~$
```

```
docker exec -it unifi-video /bin/bash
root@unifi-video:/# ls -la /var/lib/unifi-video/
total 252
drwxrwxr-x 7 unifi-video unifi-video   4096 Sep  4 19:54 .
drwxr-xr-x 1 root        root          4096 Jul 10 16:03 ..
drwxrwxr-x 3 unifi-video unifi-video   4096 Sep  4 19:50 backup
-rw------- 1 unifi-video unifi-video   2387 Sep  4 19:49 cam-keystore
drwxrwxr-x 4 unifi-video unifi-video  12288 Sep  4 23:31 db
-rw------- 1 unifi-video unifi-video   2386 Sep  4 19:49 keystore
drwxrwxr-x 3 unifi-video unifi-video   4096 Sep  4 23:29 logs
-rwxrwxr-x 1 unifi-video unifi-video    162 Sep  4 19:47 perms.txt
drwxrwxr-x 3 unifi-video unifi-video   4096 Sep  4 19:54 snapshot
-rwxrwxr-x 1 unifi-video unifi-video    235 Sep  4 19:50 system.properties
-rw------- 1 unifi-video unifi-video 204517 Sep  4 19:49 ufv-truststore
drwxr-xr-x 2 root        root          4096 Sep  4 23:06 videos
```

The videos folder from the volumes mount is mounted as root, which prevents unifi video from writing to it. 

It looks like this is attempted by [run.sh line 60](https://github.com/pducharme/UniFi-Video-Controller/blob/master/run.sh#L60)
