### ISSUE TITLE
Feature Addition: External Mongo

### ISSUE THREAD

**Issue by nmarus** [pducharme/UniFi-Video-Controller#183]
Great repo. Lots of good reference here. I was able to modify your setup to use an external Mongo container and thought I would share if you (or others) may be trying to do something similar.

The system.properties file will need these lines added to it and the docker-compose file can reference a mongo service that will then be used.

```
app.db.host=mongo
app.db.port=27017
db.external='true'
db.name=av
db.use_wiredtiger=true
```

Of note... the `db.external` value must be quoted as a string and not a boolean. I figured this out after a LOT of trial and error.

**Comment by fryfrog** [comment]
This would be a pretty decent wiki article, if you're up for it. Maybe w/ a little more detail? Gonna close the issue though. :)

**Comment by nmarus** [comment]
Might be able to do that, but in the meantime, here is a docker-compose file with the setup working.

```yaml
version: '3.2'
services:
  mongo:
    image: mongo:latest
    networks:
      - unifi
    volumes:
      - unifi_db:/data/db
  controller:
    image: jacobalberty/unifi:latest
    depends_on:
      - mongo
    networks:
      - unifi
    volumes:
      - unifi_data:/unifi/data
      - unifi_log:/unifi/log
      - unifi_cert:/unifi/cert
      - unifi_init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    depends_on:
      - controller
    networks:
      - unifi
    command: bash -c 'while [ ! -f /logs/*.log ]; do echo "Waiting for logs..."; sleep 1; done; tail -F /logs/*.log'
    volumes:
      - unifi_log:/logs:ro

volumes:
  unifi_db:
  unifi_data:
  unifi_log:
  unifi_cert:
  unifi_init:

networks:
  unifi:
```
