### ISSUE TITLE
Video doesn't start recording automatically after the unifi-video container restart. 

### ISSUE THREAD

**Issue by thomasjslin** [pducharme/UniFi-Video-Controller#188]
I set the video record mode as "always record", but it does not start recording automatically after the unifi-video container restart. I have to **remove** the unifi-video container and re-install it to make it in recording mode. 

NAS: Synology DS1618+
Docker version: Docker version 18.09.8, build bfed4f5
UniFi-Video-Controller(beta version): docker pull pducharme/unifi-video-controller:beta
Note: My UVC G3 Flex, frimware: v4.22.13 can't be detected in version 4.10.11

Log from stop to start: 

[unifi-video.txt](https://github.com/pducharme/UniFi-Video-Controller/files/4724583/unifi-video.txt)

**Comment by thomasjslin** [comment]
My install command:

docker run -d \
   --name unifi-video \
   --cap-add DAC_READ_SEARCH \
   -p 10001:10001 \
   -p 1935:1935 \
   -p 6666:6666 \
   -p 7080:7080 \
   -p 7442:7442 \
   -p 7443:7443 \
   -p 7444:7444 \
   -p 7445:7445 \
   -p 7446:7446 \
   -p 7447:7447 \
   -v /volume1/docker/unifi-video/data:/var/lib/unifi-video \
   -v /volume1/docker/unifi-video/videos:/var/lib/unifi-video/videos \
   -v /volume1/docker/unifi-video/logs:/var/log/unifi-video \
   --tmpfs /var/cache/unifi-video \
   -e TZ=Asia/Taipei \
   -e PUID=99 \
   -e PGID=100 \
   -e CREATE_TMPFS=no \
   -e DEBUG=1 \
   pducharme/unifi-video-controller:beta

**Comment by fryfrog** [comment]
When updating, one would normally *remove* the old container. I actually run mine with the `--rm` option to make this more obvious. What do you mean by "reinstall"? Do you have to re-run all the unifi video setup? Or just re-run the Docker command?

**Comment by thomasjslin** [comment]
I meant reinstall is re-run the docker command. The problem would be the video won't start recording automatically if the NAS recover by UPS power. I have to re-run the docker command manually. If I don't aware the the NAS has been restart, the recording won't be start.

**Comment by thoschworks** [comment]
I have similar issues on a Linux host after reboot. I think it is something like Issue #178 

I would suggest that you peek into your container (`docker exec -it <container name> /bin/bash`) when the failure accors and look if `/var/cache/unifi-video/hls` is existing.

If there is any mechanism on your platform to invoke a script at the end of the boot process you can add script which is destroying and restarting the container.

**Comment by dukekautington3rd** [comment]
I believe I have this issue as well.  When my server reboots (hard or soft) my container comes up and seemingly works 100% except for recording (I use on motion only but never records until I destroy/rebuild the container).
`docker-compose down && docker-compose up -d` and my video records again.  Not sure why this happens.

Here is my compose file:
```
version: '3'

services:
  unifi-nvr:
    image: pducharme/unifi-video-controller:latest
    restart: always
    networks:
     vlan2:
      ipv4_address: 172.16.10.158
    environment:
      - TZ=America/Chicago
      - DEGUG=1
      - CREATE_TMPFS=no
      - PUID=99
      - PGID=100
    tmpfs:
      - /var/cache/unifi-video/hls
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - config:/var/lib/unifi-video
      - /LARGE/nvr-videos:/var/lib/unifi-video/videos

networks:
  vlan2:
    external:
      name: vlan2

volumes:
  config:
```
